(ns deflate.core-test
  "Validates the pure-cljc inflater against fixtures generated by the JVM's
   Deflater. The *library* never touches java.util.zip — only this test
   does, purely to manufacture known-good compressed input."
  (:require [clojure.test :refer [deftest is testing]]
            [deflate.core :as inf]))

(defn- ->ubytes [^bytes ba] (mapv #(bit-and (int %) 0xff) ba))

(defn- zlib-compress [^bytes in]
  (let [d   (java.util.zip.Deflater.)
        out (java.io.ByteArrayOutputStream.)
        buf (byte-array 8192)]
    (.setInput d in)
    (.finish d)
    (while (not (.finished d))
      (let [n (.deflate d buf)] (.write out buf 0 n)))
    (.end d)
    (->ubytes (.toByteArray out))))

(deftest zlib-roundtrip
  (testing "fixed + dynamic + back-reference paths across sizes/contents"
    (doseq [s ["hello"
               "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
               "The quick brown fox jumps over the lazy dog."
               (apply str (repeat 300 "kasane 重ね データ駆動 "))]]
      (let [orig (->ubytes (.getBytes ^String s "UTF-8"))]
        (is (= orig (inf/inflate (zlib-compress (.getBytes ^String s "UTF-8"))))
            (str "len=" (count orig)))))
    (testing "all 256 byte values"
      (let [orig (vec (range 0 256))
            ba   (byte-array (map #(unchecked-byte %) orig))]
        (is (= orig (inf/inflate (zlib-compress ba))))))))

(deftest raw-deflate-roundtrip
  (testing "inflate-raw on a raw (headerless) deflate stream"
    (let [s    "raw deflate roundtrip test string, raw deflate roundtrip"
          orig (->ubytes (.getBytes ^String s "UTF-8"))
          d    (java.util.zip.Deflater. java.util.zip.Deflater/DEFAULT_COMPRESSION true)
          out  (java.io.ByteArrayOutputStream.)
          buf  (byte-array 8192)]
      (.setInput d (.getBytes ^String s "UTF-8"))
      (.finish d)
      (while (not (.finished d)) (let [n (.deflate d buf)] (.write out buf 0 n)))
      (.end d)
      (is (= orig (inf/inflate-raw (->ubytes (.toByteArray out))))))))
